language: node_js
node_js:
    - "5.3"
    - "4.2"
    - "0.12"
    - "0.10"

sudo: false

addons:
    apt:
        packages:
            - imagemagick

before_script:
    - npm install -g gulp
    - npm install -g bower
    - bower install

script: gulp

after_script: ls web

notifications:
    email: false
